version: '3'
services:
  sidecar:
    image: public.ecr.aws/g0r8j2n2/lekko/sidecar:v0.0.14
    command:
      - --repo-path=/root/example/
      - --mode=static
    container_name: sidecar-example
    volumes:
      - ../example/:/root/example/
    ports:
      - "127.0.0.1:50051:50051"
